services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 sharapov_fit.wsgi:application
    volumes:
      - ./sharapov_fit:/app  # Монтируем код проекта
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - web
    restart: unless-stopped

volumes:
  static_volume:
  media_volume: