version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 sharapov_fit.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/sharapov_fit/staticfiles
      - media_volume:/app/sharapov_fit/media
    expose:
      - 8000
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/sharapov_fit/staticfiles
      - media_volume:/app/sharapov_fit/media
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Монтируем сертификаты с хоста
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: unless-stopped

volumes:
  static_volume:
  media_volume: