# Generated by Django 5.2.6 on 2025-09-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='SLUG')),
                ('short_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Краткое описание')),
                ('is_active_promo', models.BooleanField(default=False, verbose_name='Активное промо?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promo/promocarousel/', verbose_name='Изображение')),
            ],
        ),
    ]
