# Generated by Django 5.2.6 on 2025-09-16 13:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocarousel',
            options={'verbose_name': 'Промо карусель', 'verbose_name_plural': 'Промо карусели'},
        ),
        migrations.AlterField(
            model_name='promocarousel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='SLUG'),
        ),
    ]
