# Generated by Django 5.2.6 on 2025-09-16 13:52

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_alter_promocarousel_options_alter_promocarousel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoSelfIntroduces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True, verbose_name='SLUG')),
                ('short_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Краткое описание')),
                ('is_active_promo', models.BooleanField(default=False, verbose_name='Активное промо?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promo/promocarousel/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Промо личный пример',
                'verbose_name_plural': 'Промо личные примеры',
            },
        ),
        migrations.AlterField(
            model_name='promocarousel',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True, verbose_name='SLUG'),
        ),
    ]
