# Generated by Django 5.2.6 on 2025-09-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0003_promoselfintroduces_alter_promocarousel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoselfintroduces',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promo/selfintroduces/', verbose_name='Изображение'),
        ),
    ]
