# Generated by Django 5.2.6 on 2025-09-17 13:57

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_alter_promoselfintroduces_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoSelfBeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True, verbose_name='SLUG')),
                ('short_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Краткое описание')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный?')),
                ('video', models.FileField(blank=True, null=True, upload_to='promo/videos/selfbeforeafter', verbose_name='Видео файл')),
            ],
            options={
                'verbose_name': 'Видео до и после',
                'verbose_name_plural': 'Видео до и после',
            },
        ),
    ]
