# Generated by Django 5.2.6 on 2025-09-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='full_description',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='full_description',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='short_description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(to='courses.coursecategory', verbose_name='Категории'),
        ),
    ]
