# Generated by Django 5.2.6 on 2025-09-16 19:38

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_full_description_course_short_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True, verbose_name='SLUG')),
                ('short_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Полное описание')),
            ],
            options={
                'verbose_name': 'Тэг курса',
                'verbose_name_plural': 'Тэги курсов',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(to='courses.coursetag', verbose_name='Тэги'),
        ),
    ]
