# Generated by Django 5.2.6 on 2025-09-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursetag_course_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='courses.coursecategory', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='courses.coursetag', verbose_name='Тэги'),
        ),
    ]
