# Generated by Django 5.2.6 on 2025-09-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_categories_alter_course_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_logo',
            field=models.ImageField(blank=True, null=True, upload_to='courses/courses_logo/', verbose_name='Изображение'),
        ),
    ]
